modLoader="javafml"
loaderVersion="[43,)"
license="All rights reserved"
issueTrackerURL="https://github.com/castlele/MissedBundle/issues"

[[mods]]

modId="missedbundle"
version="${file.jarVersion}"
displayName="Missed Bundle"

# TODO:
# Update when published
#updateJSONURL=""
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/"

logoFile="examplemod.png"
authors="With love from castlelecs: https://github.com/castlele"

# TODO:
# Update from readme
description='''
'''